name: Sync to Gitee
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Async Github Branch To Gitee
        uses: shanghaobo/github-branch-gitee@master
        with:
          github_repo: bty834/bty834.github.io
          github_branch: main
          gitee_repo: bao-tingyu/baotingyu.gitee.io.git
          gitee_branch: master
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
